### ISSUE TITLE
Marketing Checklist

### ISSUE THREAD

**Issue by AnalogJ** [AnalogJ/quietthyme.api#61]
From https://www.sideprojectchecklist.com/marketing-checklist/

### Market Research

> _If we knew what were doing it wouldn’t be called research._ - Albert Einstein

#### Competitive Landscape

- [ ] Make a list of competitive/alternative services.

  ##### Finding competitors
  - [ ] [Alexa](http://www.alexa.com/find-similar-sites)
  - [ ] [AlternativeTo](https://alternativeto.net)
  - [ ] [AngelList](https://angel.co/)
  - [ ] [Product Hunt](https://www.producthunt.com/)
  - [ ] [SimilarSites](http://www.similarsites.com/)
  - [ ] [SimilarWeb](https://www.similarweb.com/)
  - [ ] [Sitegur](http://sitegur.com/)
  
  ##### Competitor data to collect
  - [ ] Link to their website.
  - [ ] "One-liners" and taglines competitors use.
  - [ ] Pricing and business model.
  - [ ] Blog/RSS link.
  - [ ] Social media links.
  - [ ] Key employees on social media.

- [ ] Subscribe to RSS feeds of your competitors' blogs.
- [ ] Follow your competitors and their key employees on social media.
- [ ] Set up [Google News alerts](https://www.google.com/alerts) for competitors.
- [ ] Set up [Site Alerts](http://sitealerts.com/) for competitors.
- [ ] Subscribe to industry newsletters, magazines, trade journals etc.

#### Customer Research

- [ ] Find people in your contact list who might be future customers. Get their feedback on your idea.
- [ ] Attend meetups or conferences for your target market.
- [ ] Meet another entrepreneur who has a similar or competitive product.
- [ ] Make a list of your competitors' customers:

  ##### Finding competitors' customers
  - [ ] Check their Twitter followers, mentions.
  - [ ] Look through their Facebook fans.
  - [ ] Find people who follow them on Linkedin.
  - [ ] Check their website. Some companies list customer stories on their websites.

- [ ] Reach out to your competitors' customers, find out what they like/don't like.
- [ ] Create an "early access" list for potential future customers.

### PR Preparations

- [ ] Create list of tech, startup, and industry blogs.
- [ ] Create list of local small business journals (eg: [Crain's Chicago](http://www.chicagobusiness.com/section/Contact-Us&template=mobile)).
- [ ] Create list of local bloggers and journalists in your industry.
- [ ] Create a "Media Kit" page ([check out this example](https://www.kickresume.com/mediakit/)).

### Landing Page

- [ ] Come up with a name and domain name.
- [ ] Write a site tagline and elevator pitch.
- [ ] Create a logo.
- [ ] Set up a landing page.

  ##### Landing page tools
  - [ ] [Unbounce](https://unbounce.com/)
  - [ ] [Squarespace](https://www.squarespace.com/)
  - [ ] [Rocketpages](http://www.rocketpages.net/)
  - [ ] [Launchrock](https://www.launchrock.com/)
  - [ ] [Github Pages and Jekyll](https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/)

- [ ] Create "About" and "Contact" pages.
- [ ] Create pricing page:

  ##### Pricing ideas
  - [ ] Create a free or trial tier for your paid product.
  - [ ] Offer a 100% satisfaction/money-back guarantee.
  - [ ] Make product invite-only to start.
  - [ ] Offer free/discounted access for early adopters/beta testers.

- [ ] Add social media follow links to landing page.
- [ ] Set up analytics to learn about who signs up, bounces, etc.

  ##### Analytics platforms
  - [ ] [Google Analytics](https://analytics.google.com)
  - [ ] [Mixpanel](https://mixpanel.com/)
  - [ ] [Kiss Metrics](https://www.kissmetrics.com/)
  - [ ] [Webmaster Tools](https://www.google.com/webmasters/tools)

### Email Setup

- [ ] Set up email address to send and receive emails.
- [ ] Set up email list and signup form.

  ##### Email list services
  - [ ] [Mailchimp](https://mailchimp.com/)
  - [ ] [Mad Mimi](https://madmimi.com/)
  - [ ] [Constant Contact](https://www.constantcontact.com/home/signup.jsp)
  - [ ] [FreshMail](https://freshmail.com/)
  - [ ] [Buttondown](https://buttondown.email)

- [ ] Create a standard email template for your brand.
- [ ] Create transactional emails for when users sign up/purchase.

### Blog Setup

> _Content Marketing is all the marketing that’s left._ - Seth Godin

- [ ] Choose a blogging platform:

  ##### Blogging platforms
  - [ ] [ButterCMS](https://buttercms.com)
  - [ ] [Linkedin](https://www.linkedin.com/post/new)
  - [ ] [Medium](https://medium.com/new-story)
  - [ ] [Tumblr](https://www.tumblr.com/)
  - [ ] [Ghost](https://ghost.org/)
  - [ ] [Squarespace](https://www.squarespace.com/)
  - [ ] [Wordpress.com](https://wordpress.org/)
  
- [ ] Research keywords that you'd like your site/blog to rank for.
- [ ] Create anchor posts or pages for keywords you'd like to rank for.
- [ ] Have a blog post brainstorming session:
  
  ##### Blog post ideas
  - Little known features of your product.
  - Highlight use cases for your product.
  - Highlight customers who are using your product.
  - Interview industry specialists.
  - List of popular sites in your industry (be sure to notify them after you publish it!)
  - See these lists of ideas from [Buffer](https://blog.bufferapp.com/blogpost-ideas) and [Hubspot](https://blog.hubspot.com/blog/tabid/6307/bid/23973/41-fresh-blog-post-ideas-for-your-company-blog.aspx).

- [ ] Add email signup form or link to all blog posts.
- [ ] Add social media follow links to all blog posts.

### Social Media Setup

- [ ] Search for availability of names on social networks using [KnowEm](http://knowem.com/).
- [ ] Choose the social media accounts you'll use:

  ##### Social media platforms
  - [ ] Facebook
  - [ ] Twitter
  - [ ] Linkedin
  - [ ] Pinterest
  - [ ] Instagram
  - [ ] Snapchat
  - [ ] YouTube
  
- [ ] Standardize profile image, background photo, links and call to action across social channels.
- [ ] Join [Triberr](https://triberr.com/).
- [ ] Put premium content behind "[pay with a tweet](https://www.paywithatweet.com/)".

### Customer Outreach

> _You should be talking to a small number of users who are seriously interested in what you’re making, not a broad audience who are on the whole indifferent._ - Jessica Livingston, Founding Partner at Y Combinator

- [ ] Send a coupon code to close friends and family members to let them try your product.
- [ ] Send early access notification to customers identified in research.
- [ ] Reach out to your social media followers, ask them to try your product.
- [ ] Cold call ~20 people who might be good customers.
- [ ] Connect with potential customers on Linkedin, reach out when they accept.
- [ ] Watch a first time user use your product.
- [ ] Ask your customers for feedback directly (individual outreach).
- [ ] Run an early-stage cold email campaign.

  ##### An early-stage cold email campaign
  - [ ] Make a list of 30 prospective early customers' email addresses.
  - [ ] Send three cold emails per day for ten days. Experiment with messaging, take note of what works.
  - [ ] Send three follow up emails per day for ten days. Experiment with messaging, take note of what works.
  - [ ] Scale it up. Find more prospects, set up an automated drip campaign, rinse and repeat every month.

### Free Promotional Channels

> _I don't care how much money you have, free stuff is always a good thing._ - Queen Latifah

- [ ] Post your product on directories and review sites (Matt McCaffrey has compiled [a great list on Github](https://github.com/mmccaff/PlacesToPostYourStartup)).
- [ ] Write and distribute a Press Release.
- [ ] Write and distribute an eBook, exchange it for email signup.
- [ ] Write and distribute a white paper, exchange it for email signup.
- [ ] Give free access to influential bloggers in the industry.
- [ ] Build a "best of" page with your best blog posts that you wrote or contributed to other sites (ProBlogger calls this a "[Sneeze Page](https://problogger.com/create-a-sneeze-page-and-propel-readers-deep-within-your-blog/)").
- [ ] Make sure all blog posts have high quality images.

  ##### Places to get free stock images
  - [ ] [Unsplash](https://unsplash.com/)
  - [ ] [Skuawk](http://skuawk.com/index.html)
  - [ ] [Pexels](https://www.pexels.com/)

### Paid Promotional Channels

> _Many people take no care of their money till they come nearly to the end of it, and others do just the same with their time._ - Johann Wolfgang von Goethe

- [ ] Paid social and search advertising 

  ##### Social and search advertising platforms
  - [ ] [Google Adwords](https://adwords.google.com/home/)
  - [ ] [Linkedin](https://business.linkedin.com/marketing-solutions/ads)
  - [ ] [Facebook](https://www.facebook.com/business/products/ads)
  - [ ] [Bing](https://secure.bingads.microsoft.com/)
  - [ ] [7search](http://7search.com/)
  - [ ] [Twitter](https://ads.twitter.com/)
  - [ ] [StumbleUpon](http://ads.stumbleupon.com/)
  - [ ] [Pinterest](https://ads.pinterest.com/)
  - [ ] [Instagram](https://business.instagram.com/advertising)
  - [ ] [Launchbit](https://www.launchbit.com/)
  - [ ] [Izea](https://izea.com/)
  - [ ] [SponsoredReviews.com](http://www.sponsoredreviews.com/)

- [ ] Commission based advertising

  ##### Commission/affiliate advertising platforms
  - [ ] [Commission Junction](http://www.cj.com/advertiser)
  - [ ] [Affiliate.com](http://www.affiliate.com/)
  - [ ] [Rakuten Marketing](https://rakutenmarketing.com/affiliate)
  
- [ ] Sponsor a local meetup or conference for your target customers.
- [ ] Sponsor podcasts your customers might be listening to.
- [ ] Sponsor/advertise an industry newsletter (check out [Newsletter.city](https://newsletter.city/)).
- [ ] Set up a user referral marketing system (try [this open source app](https://github.com/harrystech/prelaunchr) or [this list of paid apps](https://upcity.com/blog/top-20-referral-marketing-apps-for-business/)).
- [ ] Run an engagement contest with prizes or free products for winners.
- [ ] Buy email or lead lists.

### Blogging

> _Blogging is like work, but without coworkers thwarting you at every turn._ - Scott Adams

- [ ] Build/update publishing calendar for your blog.
- [ ] Regularly post blog posts on your blog(s).
- [ ] Solicit guest posts from early customers and fans of your product.
- [ ] Repurpose existing blog posts:

  ##### Repurposing blog posts
  - [ ] Record/post video of you reading the post on YouTube.
  - [ ] Turn posts into a podcast.
  - [ ] Create an infographic based on the post.
  - [ ] Create a [Slideshare](https://www.slideshare.net/) or [Prezi](https://prezi.com/) of your post.

- [ ] Promote your blog content:
  
  ##### Blog promotion techniques
  - [ ] Send post to your email list.
  - [ ] Promote on your social media.
  - [ ] Email friends and relatives, ask them to share if relevant.
  - [ ] Send to other bloggers for feedback, ask to share if they like it.
  - [ ] Add your latest blog post or landing page to your email signature.

### Email

> _Email is the Jason Bourne of online: somebody’s always trying to kill it. It can’t be done._ - Unknown

- [ ] Send a regular email newsletter with blog posts, use cases, customer stories, etc.
- [ ] Promote email list on social media.
- [ ] Send 20 cold emails per week to connect with early customers and get direct feedback.
- [ ] Send new users a personal email introducing yourself.

### Social Media

> _We have technology, finally, that for the first time in human history allows people to really maintain rich connections with much larger numbers of people._ – Pierre Omidyar

- [ ] Set up automated regular social media posts.

  ##### Social media automation tools
  - [ ] [Hootsuite](https://hootsuite.com/)
  - [ ] [Sprout Social](https://sproutsocial.com/)
  - [ ] [Buffer](https://buffer.com/)
  - [ ] [Recurpost](https://recurpost.com/)

- [ ] Join Facebook and Linkedin groups where your product might be beneficial.
- [ ] Send exclusive offers to LinkedIn/Facebook Group owners.
- [ ] Join Twitter chats related to your industry/product.
- [ ] Show what happening "behind the scenes" at your project on social media (eg: pictures of your workspace, in-development features, etc.).
- [ ] Build/update publishing calendar for social media.
- [ ] Post blog posts from your blog (or partners' blogs).
- [ ] Give early users discounts for taking pics with your product.

### Public Relations

> _The art of publicity is a black art; but it has come to stay, and every year adds to its potency._ – Thomas Paine

- [ ] Ask bloggers with list articles to add your site to their content.
- [ ] Reach out to small business journals, reporters, bloggers. Inform and ask for coverage.
- [ ] Find professors and students with `.edu` sites to link to your content (good for SEO).
- [ ] Find reviews or lists of similar products. Ask to be added or leave a comment about your product.
- [ ] Guest post on other blogs.

  ##### Guest posting
  - [ ] Build a list of blogs that are a good fit for your product and accept guest posts. Save their contact form/information.
  - [ ] Write a few posts on your own blog first (to use as a demonstration).
  - [ ] Create a list of "pitches," blog post ideas with a title and one paragraph summary that might grab bloggers.
  - [ ] Pitch the blogs one idea each. See what they respond to.
  - [ ] Help promote your posts via social media, email lists, etc.
  - [ ] Reach back out in a month and try another pitch. Try to become a "regular"

- [ ] Leave non-spammy comments on blog posts related to your industry or product.
- [ ] Join and participate in forums related to your product or industry.

### External Sites

- [ ] Answer relevant questions on Q&A community sites (check back regularly)
  
  ##### Q&A Communities
  - [ ] [Stack Overflow](https://stackoverflow.com/)
  - [ ] [Quora](https://www.quora.com/)
  - [ ] Industry or geographically specific forums

- [ ] Leave comments on Slideshare presentations.
- [ ] Review industry-related books on Amazon, Goodreads.
- [ ] Write how-to guides/videos related to your product/industry:

  ##### How-to sites
  - [ ] [Snapguide](https://snapguide.com/)
  - [ ] [Guides.co](http://guides.co/)
  - [ ] [eHow](http://www.ehow.com/write-for-ehow/)
  - [ ] [Lynda](https://www.lynda.com/)
  - [ ] [Pluralsight](https://www.pluralsight.com/teach)
  - [ ] [Skillshare](https://www.skillshare.com/)
  - [ ] [Udemy](https://www.udemy.com/)

## Optimizations

- [ ] Run a customer poll (can also generate content for your blog or social media channels).
- [ ] Create another side project to promote your product ([read more](https://medium.com/swlh/side-product-marketing-is-the-new-king-a75c4ed0c0c5)).
- [ ] A/B test your landing/payment pages (check out [Optimizely](https://www.optimizely.com/)).
- [ ] A/B test email newsletters and promotions.
- [ ] Implement [Twitter cards](https://dev.twitter.com/cards/overview) on your blog posts.
- [ ] Implement [rich snippets in Google search results](https://developers.google.com/search/docs/guides/mark-up-content).
- [ ] Collect and show testimonials from your happy users.
- [ ] Analyze user signup flow ([check out the teardowns here](http://www.useronboard.com/)).
- [ ] Test your website on multiple platforms, make sure speed is good.
- [ ] Use [Website Grader](https://website.grader.com/) to pinpoint website improvements.
- [ ] Create and track weekly traffic and growth goals.
- [ ] Time social media posts and email newsletters to when your audience is most likely to respond.
- [ ] Make sure each page on your site has a clear call-to-action.
- [ ] Implement live chat to capture leads and allow them to ask questions ([Intercom](https://www.intercom.com/) seems to be the most popular).
- [ ] Segment traffic by source and audit conversion rates.
- [ ] Set up automatic analytics reports to be emailed to you each week.
- [ ] Experiment with various signup form locations, colors, and sizes.
- [ ] Add "Exit Intent" popup to your blog/site.
- [ ] Create an FAQs page.
